---
kind: pipeline
type: docker
name: linux - arm - Julia 1.0

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: julia:1.0
  commands:
  - julia --project=. --check-bounds=yes --color=yes -e 'using InteractiveUtils; versioninfo(); using Pkg; Pkg.build(); Pkg.test(coverage=true)'

---
kind: pipeline
type: docker
name: linux - arm64 - Julia 1.0

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: julia:1.0
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN
  commands:
  - julia --project=. --check-bounds=yes --color=yes -e 'using InteractiveUtils; versioninfo(); using Pkg; Pkg.build(); Pkg.test(coverage=true)'
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit_local(process_folder())'

---
kind: pipeline
type: docker
name: linux - arm - Julia 1

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: julia:1
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN
  commands:
  - julia --project=. --check-bounds=yes --color=yes -e 'using InteractiveUtils; versioninfo(); using Pkg; Pkg.build(); Pkg.test(coverage=true)'
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit_local(process_folder())'

---
kind: pipeline
type: docker
name: linux - arm64 - Julia 1

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: julia:1
  environment:
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN
  commands:
  - julia --project=. --check-bounds=yes --color=yes -e 'using InteractiveUtils; versioninfo(); using Pkg; Pkg.build(); Pkg.test(coverage=true)'
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit_local(process_folder())'
