language: julia
os:
    - osx
    - linux
    - windows
julia:
    - 1.0
    - 1.4 # explicitly specify 1.4 instead of 1 as a workaround
    - nightly
notifications:
    email: false
jobs:
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
after_success:
    - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
